FROM node:18-alpine AS base

# Stage 1: Development (dependencies + source code)
FROM base AS development

WORKDIR /usr/src/app
COPY --chown=node:node yarn.lock package*.json ./
RUN yarn install
COPY --chown=node:node . .
USER node

###################
# Stage 2: Build (production-ready code)
###################
FROM base AS build

WORKDIR /usr/src/app
COPY package.json yarn.lock tsconfig.build.json tsconfig.json ./
COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules
COPY --chown=node:node . .

RUN yarn build && yarn pkg

USER node

###################
# Stage 3: Production (minimal runtime)
###################
FROM debian:bullseye-slim

ENV NODE_ENV=production

COPY --from=build /usr/src/app/nestjs-gateway /usr/local/bin/app
RUN chmod +x /usr/local/bin/app

CMD ["app"]