FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY src/ ./src/

RUN go build -o gin-app ./src/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/gin-app .

EXPOSE 8080

CMD ["./gin-app"]