services:
  api-java:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api-java
    restart: always
    ports:
      - "8087:8087"

  postgres-service:
    container_name: postgres-service
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
#    volumes:
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql