services:
  api-nestjs:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api-nestjs
    ports:
      - "3000:8080"
    environment:
      - RABBITMQ_URL=amqp://apicconn:root@rabbitmq:5672
